const accountConstants = {
  AUTHENTICATE_REQUEST: 'ACCOUNT_AUTHENTICATE_REQUEST',
  AUTHENTICATE_SUCCESS: 'ACCOUNT_AUTHENTICATE_SUCCESS',
  AUTHENTICATE_FAILURE: 'ACCOUNT_AUTHENTICATE_FAILURE',

  LOGIN_REQUEST: 'ACCOUNT_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'ACCOUNT_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'ACCOUNT_LOGIN_FAILURE',

  DEMO_LOGIN_REQUEST: 'ACCOUNT_DEMO_LOGIN_REQUEST',
  DEMO_LOGIN_SUCCESS: 'ACCOUNT_DEMO_LOGIN_SUCCESS',
  DEMO_LOGIN_FAILURE: 'ACCOUNT_DEMO_LOGIN_FAILURE',

  LOGIN_GOOGLE_REQUEST: 'ACCOUNT_LOGIN_GOOGLE_REQUEST',
  LOGIN_GOOGLE_SUCCESS: 'ACCOUNT_LOGIN_GOOGLE_SUCCESS',
  LOGIN_GOOGLE_FAILURE: 'ACCOUNT_LOGIN_GOOGLE_FAILURE',

  LOGIN_FACEBOOK_REQUEST: 'ACCOUNT_LOGIN_FACEBOOK_REQUEST',
  LOGIN_FACEBOOK_SUCCESS: 'ACCOUNT_LOGIN_FACEBOOK_SUCCESS',
  LOGIN_FACEBOOK_FAILURE: 'ACCOUNT_LOGIN_FACEBOOK_FAILURE',

  LOGOUT: 'ACCOUNT_LOGOUT',

  REGISTER_REQUEST: 'ACCOUNT_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'ACCOUNT_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'ACCOUNT_REGISTER_FAILURE',

  VERIFY_EMAIL_REQUEST: 'ACCOUNT_VERIFY_EMAIL_REQUEST',
  VERIFY_EMAIL_SUCCESS: 'ACCOUNT_VERIFY_EMAIL_SUCCESS',
  VERIFY_EMAIL_FAILURE: 'ACCOUNT_VERIFY_EMAIL_FAILURE',

  CHANGE_PASSWORD_REQUEST: 'ACCOUNT_CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'ACCOUNT_CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'ACCOUNT_CHANGE_PASSWORD_FAILURE',

  RESET_PASSWORD_REQUEST: 'ACCOUNT_RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'ACCOUNT_RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'ACCOUNT_RESET_PASSWORD_FAILURE',

  VALIDATE_RESET_TOKEN_REQUEST: 'ACCOUNT_VALIDATE_RESET_TOKEN_REQUEST',
  VALIDATE_RESET_TOKEN_SUCCESS: 'ACCOUNT_VALIDATE_RESET_TOKEN_SUCCESS',
  VALIDATE_RESET_TOKEN_FAILURE: 'ACCOUNT_VALIDATE_RESET_TOKEN_FAILURE',
  VALIDATE_RESET_TOKEN_RESET: 'ACCOUNT_VALIDATE_RESET_TOKEN_RESET',

  UPDATE_REQUEST: 'ACCOUNT_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'ACCOUNT_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'ACCOUNT_UPDATE_FAILURE',

  GETDETAILS_REQUEST: 'ACCOUNT_GETDETAILS_REQUEST',
  GETDETAILS_SUCCESS: 'ACCOUNT_GETDETAILS_SUCCESS',
  GETDETAILS_FAILURE: 'ACCOUNT_GETDETAILS_FAILURE',

  DELETE_REQUEST: 'ACCOUNT_DELETE_REQUEST',
  DELETE_SUCCESS: 'ACCOUNT_DELETE_SUCCESS',
  DELETE_FAILURE: 'ACCOUNT_DELETE_FAILURE',
};
export default accountConstants;
