const bugConstants = {
  GET_REQUEST: 'BUG_GET_REQUEST',
  GET_SUCCESS: 'BUG_GET_SUCCESS',
  GET_FAILURE: 'BUG_GET_FAILURE',

  DELETE_REQUEST: 'BUG_DELETE_REQUEST',
  DELETE_SUCCESS: 'BUG_DELETE_SUCCESS',
  DELETE_FAILURE: 'BUG_DELETE_FAILURE',

  CREATE_REQUEST: 'BUG_CREATE_REQUEST',
  CREATE_SUCCESS: 'BUG_CREATE_SUCCESS',
  CREATE_FAILURE: 'BUG_CREATE_FAILURE',

  UPDATE_REQUEST: 'BUG_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'BUG_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'BUG_UPDATE_FAILURE',

  UPDATENOTES_REQUEST: 'BUG_UPDATENOTES_REQUEST',
  UPDATENOTES_SUCCESS: 'BUG_UPDATENOTES_SUCCESS',
  UPDATENOTES_FAILURE: 'BUG_UPDATENOTES_FAILURE',
};
export default bugConstants;
