const bugConstants = {
  DELETE_REQUEST: 'NOTE_DELETE_REQUEST',
  DELETE_SUCCESS: 'NOTE_DELETE_SUCCESS',
  DELETE_FAILURE: 'NOTE_DELETE_FAILURE',

  CREATE_REQUEST: 'NOTE_CREATE_REQUEST',
  CREATE_SUCCESS: 'NOTE_CREATE_SUCCESS',
  CREATE_FAILURE: 'NOTE_CREATE_FAILURE',

  UPDATE_REQUEST: 'NOTE_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'NOTE_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'NOTE_UPDATE_FAILURE',
};
export default bugConstants;
