const projectConstants = {
  GET_REQUEST: 'PROJECT_GET_REQUEST',
  GET_SUCCESS: 'PROJECT_GET_SUCCESS',
  GET_FAILURE: 'PROJECT_GET_FAILURE',

  DELETE_REQUEST: 'PROJECT_DELETE_REQUEST',
  DELETE_SUCCESS: 'PROJECT_DELETE_SUCCESS',
  DELETE_FAILURE: 'PROJECT_DELETE_FAILURE',

  CREATE_REQUEST: 'PROJECT_CREATE_REQUEST',
  CREATE_SUCCESS: 'PROJECT_CREATE_SUCCESS',
  CREATE_FAILURE: 'PROJECT_CREATE_FAILURE',

  UPDATE_REQUEST: 'PROJECT_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'PROJECT_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'PROJECT_UPDATE_FAILURE',

  UPDATEMEMBERS_REQUEST: 'PROJECT_UPDATEMEMBERS_REQUEST',
  UPDATEMEMBERS_SUCCESS: 'PROJECT_UPDATEMEMBERS_SUCCESS',
  UPDATEMEMBERS_FAILURE: 'PROJECT_UPDATEMEMBERS_FAILURE',

  LEAVE_REQUEST: 'PROJECT_LEAVE_REQUEST',
  LEAVE_SUCCESS: 'PROJECT_LEAVE_SUCCESS',
  LEAVE_FAILURE: 'PROJECT_LEAVE_FAILURE',
};
export default projectConstants;
